# Generated by Django 5.0.6 on 2024-05-19 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=10)),
                ('date', models.DateField()),
                ('total_revenue', models.DecimalField(decimal_places=2, max_digits=15)),
                ('ebitda', models.DecimalField(decimal_places=2, max_digits=15)),
                ('ebit', models.DecimalField(decimal_places=2, max_digits=15)),
                ('interest_expense', models.DecimalField(decimal_places=2, max_digits=15)),
                ('pretax_income', models.DecimalField(decimal_places=2, max_digits=15)),
                ('income_taxes', models.DecimalField(decimal_places=2, max_digits=15)),
                ('net_income', models.DecimalField(decimal_places=2, max_digits=15)),
                ('diluted_eps', models.DecimalField(decimal_places=2, max_digits=15)),
                ('diluted_average_shares', models.DecimalField(decimal_places=2, max_digits=15)),
                ('yoy_growth', models.DecimalField(decimal_places=2, max_digits=5)),
                ('ebitda_margin', models.DecimalField(decimal_places=2, max_digits=5)),
                ('ebit_margin', models.DecimalField(decimal_places=2, max_digits=5)),
                ('tax_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('net_margin', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                'indexes': [models.Index(fields=['ticker', 'date'], name='financials__ticker_f9bdec_idx')],
                'unique_together': {('ticker', 'date')},
            },
        ),
    ]
